export const data = [
  {
    id: 1,
    name: 'Jakaria Ahmod',
    role: 'Frontend Developer',
    email: 'jakaria@example.com',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Sarah Khan',
    role: 'Backend Developer',
    email: 'sarah@example.com',
    status: 'Inactive',
  },
  {
    id: 3,
    name: 'Rafi Ahmed',
    role: 'UI/UX Designer',
    email: 'rafi@example.com',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Nadia Islam',
    role: 'Project Manager',
    email: 'nadia@example.com',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Arif Hossain',
    role: 'DevOps Engineer',
    email: 'arif@example.com',
    status: 'Inactive',
  },
  {
    id: 1,
    name: 'Jakaria Ahmod',
    role: 'Frontend Developer',
    email: 'jakaria@example.com',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Sarah Khan',
    role: 'Backend Developer',
    email: 'sarah@example.com',
    status: 'Inactive',
  },
  {
    id: 3,
    name: 'Rafi Ahmed',
    role: 'UI/UX Designer',
    email: 'rafi@example.com',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Nadia Islam',
    role: 'Project Manager',
    email: 'nadia@example.com',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Arif Hossain',
    role: 'DevOps Engineer',
    email: 'arif@example.com',
    status: 'Inactive',
  },
  {
    id: 1,
    name: 'Jakaria Ahmod',
    role: 'Frontend Developer',
    email: 'jakaria@example.com',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Sarah Khan',
    role: 'Backend Developer',
    email: 'sarah@example.com',
    status: 'Inactive',
  },
  {
    id: 3,
    name: 'Rafi Ahmed',
    role: 'UI/UX Designer',
    email: 'rafi@example.com',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Nadia Islam',
    role: 'Project Manager',
    email: 'nadia@example.com',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Arif Hossain',
    role: 'DevOps Engineer',
    email: 'arif@example.com',
    status: 'Inactive',
  },
  {
    id: 1,
    name: 'Jakaria Ahmod',
    role: 'Frontend Developer',
    email: 'jakaria@example.com',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Sarah Khan',
    role: 'Backend Developer',
    email: 'sarah@example.com',
    status: 'Inactive',
  },
  {
    id: 3,
    name: 'Rafi Ahmed',
    role: 'UI/UX Designer',
    email: 'rafi@example.com',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Nadia Islam',
    role: 'Project Manager',
    email: 'nadia@example.com',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Arif Hossain',
    role: 'DevOps Engineer',
    email: 'arif@example.com',
    status: 'Inactive',
  },
];
