export const teamMembers = [
  {
    id: 1,
    name: 'Jakaria Ahmod',
    role: 'Frontend Developer',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: 2,
    name: 'Sarah Khan',
    role: 'Backend Developer',
    image: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: 3,
    name: 'Rafi Ahmed',
    role: 'UI/UX Designer',
    image: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: 4,
    name: 'Nadia Islam',
    role: 'Project Manager',
    image: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: 5,
    name: 'Arif Hossain',
    role: 'DevOps Engineer',
    image: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
  {
    id: 6,
    name: 'Lina Rahman',
    role: 'QA Engineer',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    id: 7,
    name: 'Shakil Ahmed',
    role: 'Fullstack Developer',
    image: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    id: 8,
    name: 'Maya Chowdhury',
    role: 'Content Writer',
    image: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    id: 9,
    name: 'Sajid Khan',
    role: 'Business Analyst',
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    id: 10,
    name: 'Tania Sultana',
    role: 'HR Manager',
    image: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
  {
    id: 11,
    name: 'Fahim Islam',
    role: 'Security Analyst',
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    id: 12,
    name: 'Rumana Akter',
    role: 'Graphic Designer',
    image: 'https://randomuser.me/api/portraits/women/12.jpg',
  },
  {
    id: 13,
    name: 'Omar Faruk',
    role: 'Mobile Developer',
    image: 'https://randomuser.me/api/portraits/men/13.jpg',
  },
  {
    id: 14,
    name: 'Nusrat Jahan',
    role: 'Marketing Specialist',
    image: 'https://randomuser.me/api/portraits/women/14.jpg',
  },
  {
    id: 15,
    name: 'Imran Hossain',
    role: 'Data Scientist',
    image: 'https://randomuser.me/api/portraits/men/15.jpg',
  },
  {
    id: 16,
    name: 'Riya Begum',
    role: 'SEO Expert',
    image: 'https://randomuser.me/api/portraits/women/16.jpg',
  },
  {
    id: 17,
    name: 'Sabbir Rahman',
    role: 'Cloud Engineer',
    image: 'https://randomuser.me/api/portraits/men/17.jpg',
  },
  {
    id: 18,
    name: 'Anika Sultana',
    role: 'Product Owner',
    image: 'https://randomuser.me/api/portraits/women/18.jpg',
  },
  {
    id: 19,
    name: 'Tanvir Ahmed',
    role: 'Scrum Master',
    image: 'https://randomuser.me/api/portraits/men/19.jpg',
  },
  {
    id: 20,
    name: 'Rasheda Akter',
    role: 'Customer Support',
    image: 'https://randomuser.me/api/portraits/women/20.jpg',
  },
];
