export const products = [
  {
    id: 1,
    name: 'iPhone 15 Pro',
    sku: 'APL-IP15P',
    quantity: 20,
    status: 'In Stock',
  },
  {
    id: 2,
    name: 'Samsung Galaxy S24',
    sku: 'SMS-S24',
    quantity: 5,
    status: 'Low Stock',
  },
  {
    id: 3,
    name: 'Google Pixel 9',
    sku: 'GGL-PX9',
    quantity: 0,
    status: 'Out of Stock',
  },
  {
    id: 4,
    name: 'iPhone 15 Pro',
    sku: 'APL-IP15P',
    quantity: 20,
    status: 'In Stock',
  },
  {
    id: 5,
    name: 'Samsung Galaxy S24',
    sku: 'SMS-S24',
    quantity: 5,
    status: 'Low Stock',
  },
  {
    id: 6,
    name: 'Google Pixel 9',
    sku: 'GGL-PX9',
    quantity: 0,
    status: 'Out of Stock',
  },
  {
    id: 7,
    name: 'iPhone 15 Pro',
    sku: 'APL-IP15P',
    quantity: 20,
    status: 'In Stock',
  },
  {
    id: 8,
    name: 'Samsung Galaxy S24',
    sku: 'SMS-S24',
    quantity: 5,
    status: 'Low Stock',
  },
  {
    id: 9,
    name: 'Google Pixel 9',
    sku: 'GGL-PX9',
    quantity: 0,
    status: 'Out of Stock',
  },
  {
    id: 10,
    name: 'iPhone 15 Pro',
    sku: 'APL-IP15P',
    quantity: 20,
    status: 'In Stock',
  },
  {
    id: 12,
    name: 'Samsung Galaxy S24',
    sku: 'SMS-S24',
    quantity: 5,
    status: 'Low Stock',
  },
  {
    id: 13,
    name: 'Google Pixel 9',
    sku: 'GGL-PX9',
    quantity: 0,
    status: 'Out of Stock',
  },
  {
    id: 14,
    name: 'iPhone 15 Pro',
    sku: 'APL-IP15P',
    quantity: 20,
    status: 'In Stock',
  },
  {
    id: 15,
    name: 'Samsung Galaxy S24',
    sku: 'SMS-S24',
    quantity: 5,
    status: 'Low Stock',
  },
  {
    id: 16,
    name: 'Google Pixel 9',
    sku: 'GGL-PX9',
    quantity: 0,
    status: 'Out of Stock',
  },
  {
    id: 17,
    name: 'iPhone 15 Pro',
    sku: 'APL-IP15P',
    quantity: 20,
    status: 'In Stock',
  },
  {
    id: 18,
    name: 'Samsung Galaxy S24',
    sku: 'SMS-S24',
    quantity: 5,
    status: 'Low Stock',
  },
  {
    id: 19,
    name: 'Google Pixel 9',
    sku: 'GGL-PX9',
    quantity: 0,
    status: 'Out of Stock',
  },
  {
    id: 20,
    name: 'iPhone 15 Pro',
    sku: 'APL-IP15P',
    quantity: 20,
    status: 'In Stock',
  },
  {
    id: 21,
    name: 'Samsung Galaxy S24',
    sku: 'SMS-S24',
    quantity: 5,
    status: 'Low Stock',
  },
  {
    id: 22,
    name: 'Google Pixel 9',
    sku: 'GGL-PX9',
    quantity: 0,
    status: 'Out of Stock',
  },
];
