export const orders = [
  {
    id: 'ORD-1001',
    name: 'John Doe',
    address: '123 Main Street, New York, NY',
    date: '2025-08-01',
    type: 'Online',
    status: 'Delivered',
  },
  {
    id: 'ORD-1002',
    name: 'Jane Smith',
    address: '456 Elm Street, Los Angeles, CA',
    date: '2025-08-02',
    type: 'In Store',
    status: 'Pending',
  },
  {
    id: 'ORD-1003',
    name: 'Michael Brown',
    address: '789 Oak Avenue, Chicago, IL',
    date: '2025-08-03',
    type: 'Online',
    status: 'Shipped',
  },
  {
    id: 'ORD-1004',
    name: 'Emily Davis',
    address: '101 Pine Street, Seattle, WA',
    date: '2025-08-04',
    type: 'Online',
    status: 'Cancelled',
  },
  {
    id: 'ORD-1001',
    name: 'John Doe',
    address: '123 Main Street, New York, NY',
    date: '2025-08-01',
    type: 'Online',
    status: 'Delivered',
  },
  {
    id: 'ORD-1002',
    name: 'Jane Smith',
    address: '456 Elm Street, Los Angeles, CA',
    date: '2025-08-02',
    type: 'In Store',
    status: 'Pending',
  },
  {
    id: 'ORD-1003',
    name: 'Michael Brown',
    address: '789 Oak Avenue, Chicago, IL',
    date: '2025-08-03',
    type: 'Online',
    status: 'Shipped',
  },
  {
    id: 'ORD-1004',
    name: 'Emily Davis',
    address: '101 Pine Street, Seattle, WA',
    date: '2025-08-04',
    type: 'Online',
    status: 'Cancelled',
  },
  {
    id: 'ORD-1001',
    name: 'John Doe',
    address: '123 Main Street, New York, NY',
    date: '2025-08-01',
    type: 'Online',
    status: 'Delivered',
  },
  {
    id: 'ORD-1002',
    name: 'Jane Smith',
    address: '456 Elm Street, Los Angeles, CA',
    date: '2025-08-02',
    type: 'In Store',
    status: 'Pending',
  },
  {
    id: 'ORD-1003',
    name: 'Michael Brown',
    address: '789 Oak Avenue, Chicago, IL',
    date: '2025-08-03',
    type: 'Online',
    status: 'Shipped',
  },
  {
    id: 'ORD-1004',
    name: 'Emily Davis',
    address: '101 Pine Street, Seattle, WA',
    date: '2025-08-04',
    type: 'Online',
    status: 'Cancelled',
  },
  {
    id: 'ORD-1001',
    name: 'John Doe',
    address: '123 Main Street, New York, NY',
    date: '2025-08-01',
    type: 'Online',
    status: 'Delivered',
  },
  {
    id: 'ORD-1002',
    name: 'Jane Smith',
    address: '456 Elm Street, Los Angeles, CA',
    date: '2025-08-02',
    type: 'In Store',
    status: 'Pending',
  },
  {
    id: 'ORD-1003',
    name: 'Michael Brown',
    address: '789 Oak Avenue, Chicago, IL',
    date: '2025-08-03',
    type: 'Online',
    status: 'Shipped',
  },
  {
    id: 'ORD-1004',
    name: 'Emily Davis',
    address: '101 Pine Street, Seattle, WA',
    date: '2025-08-04',
    type: 'Online',
    status: 'Cancelled',
  },
];
