export const mockEmails = [
  {
    id: '1',
    sender: 'Jullu Jalal',
    subject: 'Our Bachelor of Commerce program is ACBSP-accredited.',
    content:
      'Dear Student, We are excited to inform you about our accredited Bachelor of Commerce program...',
    time: '8:38 AM',
    date: '2024-01-15T08:38:00',
    category: 'Primary',
    starred: false,
    read: false,
    folder: 'inbox',
  },
  {
    id: '2',
    sender: 'Minerva Barnett',
    subject: 'Get Best Advertiser In Your Side Pocket',
    content:
      'Hello, I wanted to share some advertising strategies that could help your business...',
    time: '8:13 AM',
    date: '2024-01-15T08:13:00',
    category: 'Work',
    starred: false,
    read: true,
    folder: 'inbox',
  },
  {
    id: '3',
    sender: 'Peter Lewis',
    subject: 'Vacation Home Rental Success',
    content:
      'Hi there! I hope you are doing well. I wanted to share my experience with vacation rentals...',
    time: '7:52 PM',
    date: '2024-01-14T19:52:00',
    category: 'Friends',
    starred: true,
    read: false,
    folder: 'inbox',
  },
  {
    id: '4',
    sender: 'Anthony Briggs',
    subject: 'Free Classifieds Using Them To Promote Your Stuff Online',
    content:
      'Learn how to effectively use free classified ads to promote your products and services...',
    time: '7:52 PM',
    date: '2024-01-14T19:52:00',
    category: '',
    starred: true,
    read: true,
    folder: 'starred',
  },
  {
    id: '5',
    sender: 'Clifford Morgan',
    subject: 'Enhance Your Brand Potential With Giant Advertising Blimps',
    content:
      'Discover innovative advertising solutions that can take your brand to new heights...',
    time: '4:13 PM',
    date: '2024-01-14T16:13:00',
    category: 'Social',
    starred: false,
    read: false,
    folder: 'inbox',
  },
  {
    id: '6',
    sender: 'Cecilia Webster',
    subject: 'Always Look On The Bright Side Of Life',
    content:
      'Hey friend! Just wanted to send you some positive vibes and motivation...',
    time: '3:52 PM',
    date: '2024-01-14T15:52:00',
    category: 'Friends',
    starred: false,
    read: true,
    folder: 'inbox',
  },
  {
    id: '7',
    sender: 'Harvey Manning',
    subject: 'Curling Irons Are As Individual As The Women Who Use Them',
    content:
      'Product review and recommendations for the best curling irons in the market...',
    time: '2:30 PM',
    date: '2024-01-14T14:30:00',
    category: '',
    starred: true,
    read: false,
    folder: 'starred',
  },
  {
    id: '8',
    sender: 'Willie Blake',
    subject: 'Our Bachelor of Commerce program is ACBSP-accredited.',
    content:
      'Follow-up information about our educational programs and enrollment details...',
    time: '8:38 AM',
    date: '2024-01-13T08:38:00',
    category: 'Primary',
    starred: false,
    read: true,
    folder: 'inbox',
  },
  {
    id: '9',
    sender: 'You',
    subject: 'Re: Meeting Schedule for Next Week',
    content:
      'Thank you for the meeting invitation. I confirm my attendance for Tuesday at 2 PM...',
    time: '5:45 PM',
    date: '2024-01-12T17:45:00',
    category: 'Work',
    starred: false,
    read: true,
    folder: 'sent',
  },
  {
    id: '10',
    sender: 'You',
    subject: 'Draft: Project Proposal',
    content:
      'This is a draft of the project proposal that needs to be completed...',
    time: '3:20 PM',
    date: '2024-01-12T15:20:00',
    category: 'Work',
    starred: false,
    read: false,
    folder: 'drafts',
  },
  {
    id: '11',
    sender: 'Spam Sender',
    subject: 'You have won $1,000,000!!!',
    content: 'Congratulations! You have been selected as our lucky winner...',
    time: '11:30 AM',
    date: '2024-01-11T11:30:00',
    category: '',
    starred: false,
    read: false,
    folder: 'spam',
  },
  {
    id: '12',
    sender: 'Important Client',
    subject: 'Urgent: Contract Review Required',
    content:
      'Please review the attached contract and provide your feedback by end of day...',
    time: '9:15 AM',
    date: '2024-01-11T09:15:00',
    category: 'Work',
    starred: true,
    read: false,
    folder: 'important',
  },
];
