export const products = [
  {
    id: 1,
    image: 'https://i.ibb.co/TKmFXWN/iphone15.png',
    title: 'iPhone 15 Pro Max',
    price: 25000,
    rating: 4.9,
    reviews: 320,
    isFavorite: false,
  },
  {
    id: 2,
    image: 'https://i.ibb.co/DKwY7Ny/samsung-s23.png',
    title: 'Samsung Galaxy S23',
    price: 14000,
    rating: 4.7,
    reviews: 280,
    isFavorite: true,
  },
  {
    id: 3,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 4,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 5,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 6,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 7,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 8,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 9,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 10,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 11,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 12,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 13,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
  {
    id: 14,
    image: 'https://i.ibb.co/fFh0Bt4/sony-headphone.png',
    title: 'Sony WH-1000XM5',
    price: 7200,
    rating: 4.8,
    reviews: 150,
    isFavorite: false,
  },
];
